### ISSUE TITLE
Don't work with TL-SG1024DE : soup.script.string is None

### ISSUE THREAD

**Issue by FredThx** [psmode/essstat#4]
I try the script with a TL-SG1024DE :
python .\essstat.py  -d 192.168.10.1 -p xxxx-u FredThx
FredThx
xxxx
http://192.168.10.1
<Response [200]>
<script src="common.js" type="text/javascript"></script>
None
Traceback (most recent call last):
  File "essstat.py", line 149, in <module>
    print(pattern.search(soup.script.string).group(0))
TypeError: expected string or bytes-like object

soup.script.string is None!

please find attache the html request
[PortStatisticsRpm.htm.txt](https://github.com/psmode/essstat/files/6299672/PortStatisticsRpm.htm.txt)

**Comment by psmode** [comment]
What version of BeautifulSoup4 do you have loaded?

**Comment by psmode** [comment]
OK, nevermind about the BeautifulSoup4 version. I can really see how the vendor _really_ changed up the scripting and presentation on the TL-SG1024DE. For the TL-SG1016DE and TL-SG108E models, the data of interest was placed conveniently in a <script> block that appeared in the HTML even before the <head> block. With the TL-SG1024DE model, the data is now buried in a script block in the <body> section. 

Aside form the location change, the vendor has also changed the data assignments from a convenient form to a mess. In the older switches, we had something like:
```
state:[1,1,1,1,1,1,1,1,0,0],
link_status:[6,0,0,0,0,0,6,5,0,0],
```
with a similar array for the packet counts. 

In the TL-SG1024DE, the relevant data is put into two long strings, one for each "half" of the ports.
```
var tmp_info = "1 0 0 0 0 0 1 6 1542263 0 91644 0 1 6 1451411 0 60580 0 1 6 2484437 0 849974 0 1 0 0 0 0 0 1 0 2398513 0 1716010 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 6 3954488 0 1650984 0 1 6 29078099 0 22922999 9 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 ";
var tmp_info2 = "1 0 0 0 0 0 1 5 19806177 0 22707629 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 5 1778176 0 254766 0 1 6 11285836 0 13670990 0 1 0 0 0 0 0 ";
```
It looks like they use `port_middle_num` to break the port data into two "halves", with 16 ports in the first set and only 8 in the second (????). sigh. The vendor then has a block of javascript to portion out the six data elements for each port from the long `tmp_info `and `tmp_info2 `strings.

So this is going to take a little more effort, but certainly not impossible. Digging out the data from the body will look like:
```
pattern3 = re.compile(r'tmp_info = "(.*?)";$', re.MULTILINE | re.DOTALL)
print(pattern3.search(str(soup.body.script)).group(1))
1 0 0 0 0 0 1 6 1542263 0 91644 0 1 6 1451411 0 60580 0 1 6 2484437 0 849974 0 1 0 0 0 0 0 1 0 2398513 0 1716010 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 6 3954488 0 1650984 0 1 6 29078099 0 22922999 9 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 
```
and

```
pattern3 = re.compile(r'tmp_info2 = "(.*?)";$', re.MULTILINE | re.DOTALL)
print(pattern3.search(str(soup.body.script)).group(1))
1 0 0 0 0 0 1 5 19806177 0 22707629 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 5 1778176 0 254766 0 1 6 11285836 0 13670990 0 1 0 0 0 0 0 
```

The annoying part is that the data has the state, link status and packet counters for each port interfiled, instead of being broken into three separate sections. 

Stay tuned!

**Comment by psmode** [comment]
So it looks like a reasonable way to tell the difference in the models is to check if the first script on the returned HTML is in the <head> section with a comparison like:
`if soup.script == soup.head.script:
`
If they are the same thing, this means the first <script> section is in the <head> and there is no <script> section before the <head>, therefore, this is an TL-SG1024D. 

I don't have a five-port TL-SG105E to test, but I am thinking that the code for the lower port count switches was good enough for that unit. But if somebody has one to test against, please let me know

**Comment by psmode** [comment]
I created a branch named [TL-SG1024DE-support](https://github.com/psmode/essstat/find/TL-SG1024DE-support) with v0.5.0 for essstat.py . I'd appreciate it if people could give this updated version a try I'd appreciate it.

I have tested it in my environment with BeautifulSoup4 versions from 4.6.0 through 4.9.3. I tested it against an actual TL-SG108E as well as the data captured from a TL-SG1024DE that @FredThx supplied (Thank you!)

I'll merge this into the main branch once this is more proven out.

**Comment by psmode** [comment]
This code was mistakenly dropped from the main branch in v0.8.0. I have created another branch named [TL-SG1024DE support redux](https://github.com/psmode/essstat/find/TL-SG1024DE-support-redux) to work on re-integrating this capability in the current code.

**Comment by psmode** [comment]
I believe I have the code added back in correctly on this branch. I tested the new **essstat.py** with a TL-SG108E to ensure that I did not break the main code. However,  I do not have a TL-SG1024DE so I cannot really test that part of the logic properly.

If somebody out there with a TL-SG1024DE could give the code in this branch a try, then we can validate this functionality and get it back to the main branch.
